#!/bin/bash
set -e

# If no first argument is present, we'll create "precise64"
VAGRANT_NAME=${1:-precise64}

export PACKER_LOG=1
test -f $BOX_FILE && rm -f $BOX_FILE

packer build -only virtualbox-iso ubuntu_12.04.json

vagrant box remove ${VAGRANT_NAME} || true
vagrant box add ${VAGRANT_NAME} $BOX_FILE
