#!/bin/bash
set -e
set -x

# It's not good to hardcode this value, but unfortunately there's a bug with the
# virtualbox provisioner in conjunction with virtual-box guest additions.
VERSION=4.3.20

apt-get clean -y
apt-get update -y
apt-get install -y linux-headers-$(uname -r) build-essential dkms

# Install things required for virtualbox
mkdir /media/VBoxGuestAdditions
cd /tmp

wget http://download.virtualbox.org/virtualbox/${VERSION}/VBoxGuestAdditions_${VERSION}.iso

# TODO: This exits with non-zero always. Need to figure out why
mount -o loop,ro VBoxGuestAdditions_${VERSION}.iso /media/VBoxGuestAdditions
sh /media/VBoxGuestAdditions/VBoxLinuxAdditions.run || true

# Work around the bug
ln -s /opt/VBoxGuestAdditions-${VERSION}/lib/VBoxGuestAdditions /usr/lib/VBoxGuestAdditions

# Cleanup
rm VBoxGuestAdditions_${VERSION}.iso
umount /media/VBoxGuestAdditions
rmdir /media/VBoxGuestAdditions
